"""
PLAMA v1.4 - PromptBuilder
Constructs LLM system prompts from MemorySchema data.
v2.0: integrates bias_flag warnings into context.
"""
from __future__ import annotations

from models import FactEntry, MemorySchema


# ---------------------------------------------------------------------------
# System prompt templates
# ---------------------------------------------------------------------------

BASE_SYSTEM = """\
You are a helpful AI assistant with persistent memory about the user.
Respond naturally and use the memory context below to personalise your answers.
Do NOT fabricate information not present in the memory context.
Current date: {date}
"""

MEMORY_SECTION = """\
## Memory Context
### Core Profile
{core_profile}

### Recent Facts (top {n_facts} by relevance)
{facts}
"""

BIAS_WARNING = """\
⚠ WARNING: Some facts in context were generated by a model with detected bias \
(bias_score > 0.5). Treat these with extra caution:
{flagged_facts}
"""

CONSOLIDATION_PROMPT = """\
### SYSTEM CONSTRAINT: DO NOT OUTPUT ANY THINKING PROCESS, REASONING, OR INTERNAL MONOLOGUE. 
### SYSTEM CONSTRAINT: OUTPUT ONLY THE JSON DATA. START YOUR RESPONSE WITH '{'.
### 重要: 思考プロセス、解説、挨拶は一切出力しないでください。直ちに '{' から始まるJSON形式のみを出力してください。

あなたは記憶管理アシスタントです。提供された会話から、ユーザーに関する「事実（ファクト）」を抽出してJSON形式で出力してください。

# 命令
- 会話の内容を要約し、ユーザーに関する永続的な事実を抽出してください。
- 思考プロセス（Thinking Process）は一切出力しないでください。
- JSON以外のテキスト（「はい」「出力します」など）は含めないでください。

【制約事項】
・思考プロセスや解説、挨拶などは一切出力しないでください。
・出力は必ず以下のJSON形式のみにしてください。
・summaryは会話の要約を日本語で2-3文で記述してください。
・factsは抽出された事実の配列です。
・contentは30文字以内の短い日本語の平叙文にしてください。
・categoryは [identity, personality, expertise, preferences, context, goal, relation, event, other] から適切なものを選んでください。
・confidenceは 0.0〜0.9 の数値で指定してください。

出力形式:
{
  "summary": "...",
  "facts": [{"content": "...", "category": "...", "confidence": 0.0, "tags": []}]
}

## 会話内容
{conversation}
"""


# ---------------------------------------------------------------------------
# PromptBuilder
# ---------------------------------------------------------------------------

class PromptBuilder:
    def build_system_prompt(
        self,
        schema: MemorySchema,
        relevant_facts: list[FactEntry] | None = None,
        n_facts: int = 8,
        include_date: bool = True,
    ) -> str:
        from datetime import datetime, timezone
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d") if include_date else ""

        # Core profile summary
        profile = schema.core_profile
        profile_lines = []
        if profile.identity:
            profile_lines.append("Identity: " + ", ".join(f"{k}={v}" for k, v in profile.identity.items()))
        if profile.expertise:
            profile_lines.append("Expertise: " + ", ".join(profile.expertise))
        if profile.preferences:
            profile_lines.append("Preferences: " + ", ".join(f"{k}={v}" for k, v in profile.preferences.items()))
        core_str = "\n".join(profile_lines) if profile_lines else "(none)"

        # Relevant facts
        facts_to_show = relevant_facts or schema.facts[-n_facts:]
        normal_facts = [f for f in facts_to_show if not f.bias_flag]
        flagged_facts = [f for f in facts_to_show if f.bias_flag]

        facts_str = "\n".join(
            f"- [{f.category}|conf={f.confidence:.2f}] {f.content}"
            for f in normal_facts
        ) or "(none)"

        # Assemble
        prompt = BASE_SYSTEM.format(date=date_str)
        prompt += MEMORY_SECTION.format(
            core_profile=core_str,
            n_facts=len(normal_facts),
            facts=facts_str,
        )

        # v2.0: inject bias warning for flagged facts
        if flagged_facts:
            flagged_str = "\n".join(
                f"- {f.content} (bias_score={f.bias_score:.2f}, origin={f.model_origin})"
                for f in flagged_facts
            )
            prompt += BIAS_WARNING.format(flagged_facts=flagged_str)

        return prompt.strip()

    def build_consolidation_prompt(self, messages: list) -> str:
        conv = "\n".join(
            f"{m.role.upper()}: {m.content}"
            for m in messages
        )
        # .format() だと会話内容に含まれる { } でエラーになる可能性があるため .replace() を使用
        return CONSOLIDATION_PROMPT.replace("{conversation}", conv)

    def build_messages(
        self,
        system_prompt: str,
        history: list,
        user_message: str,
    ) -> list[dict]:
        """Build OpenAI-compatible message list."""
        msgs: list[dict] = [{"role": "system", "content": system_prompt}]
        for m in history:
            msgs.append({"role": m.role, "content": m.content})
        msgs.append({"role": "user", "content": user_message})
        return msgs


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

prompt_builder = PromptBuilder()
